defmodule DHCW360.Repo.Migrations.CreateUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :primary_manager_email_address, :text
      add :secondary_managers_email_addresses, :text
      add :direct_reports_email_addresses, :text
      add :peers_email_addresses, :text
      add :others_email_addresses, :text
    end
  end

  def down do
    alter table(:users) do
      remove :others_email_addresses
      remove :peers_email_addresses
      remove :direct_reports_email_addresses
      remove :secondary_managers_email_addresses
      remove :primary_manager_email_address
    end
  end
end
