defmodule DHCW360.Repo.Migrations.CreateItems do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :reviewer_id,
          references(:users,
            column: :id,
            name: "items_reviewer_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :reviewee_id,
          references(:users,
            column: :id,
            name: "items_reviewee_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:items, "items_reviewer_id_fkey")

    drop constraint(:items, "items_reviewee_id_fkey")

    drop table(:items)
  end
end
